development:
  adapter: postgresql
  database: tardis_project_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: tardis_project_test
  host: localhost
  min_messages: warning
  username: